const FETCH_DATA = "FETCH_DATA";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const LIST_FETCHED = "LIST_FETCHED";
const API_CALLED = "API_CALLED";
const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";
const ADD_ITEM = "ADD_ITEM";
const SUCCESS = "SUCCESS";
export const Action = { ADD_ITEM, FETCH_DATA,LIST_FETCHED,API_CALLED, CATEGORIES_FETCHED, FETCH_CATEGORIES, SUCCESS};